name: BlockDestroyer
main: me.cyberflame.blockdestroyer.BlockDestroyer
version: Version 1.0-b9105b1
description: BlockDestroyer is a plugin made by CyberFlame primarily for OuterWorlds. This was updated by StarZorrow (zorurruan) and I thank him very much for his modifications to it as the original was kinda sloppy.
author: Owner_of_Mojang (CyberFlame)
